### ISSUE TITLE
Error when generating monocular depths by DPT for the LLFF dataset

### ISSUE THREAD

**Issue by JiajieLi7012** [Fictionarry/DNGaussian#16]
Hello, I installed the environment by following the instructions and tried to generate the depths for LLFF dataset by running `python get_depth_map_for_llff_dtu.py --root_path ../data/llff/nerf_llff_data/ --benchmark LLFF` but I got the following error:

```
Using cache found in /local/home/lijiaj/.cache/torch/hub/intel-isl_MiDaS_master
/local/home/lijiaj/miniconda3/envs/dngaussian/lib/python3.7/site-packages/timm/models/_factory.py:121: UserWarning: Mapping deprecated model name vit_base_resnet50_384 to current vit_base_r50_s16_384.orig_in21k_ft_in1k.
  **kwargs,
Using cache found in /local/home/lijiaj/.cache/torch/hub/intel-isl_MiDaS_master
image_paths: [['../data/llff/nerf_llff_data/fern/images/IMG_4026.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4027.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4028.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4029.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4030.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4031.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4032.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4033.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4034.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4035.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4036.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4037.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4038.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4039.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4040.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4041.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4042.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4043.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4044.JPG', '../data/llff/nerf_llff_data/fern/images/IMG_4045.JPG'], []]
k, img.shape: 0 (3024, 4032, 3)
Traceback (most recent call last):
  File "get_depth_map_for_llff_dtu.py", line 84, in <module>
    prediction = midas(input_batch)
  File "/local/home/lijiaj/miniconda3/envs/dngaussian/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/local/home/lijiaj/.cache/torch/hub/intel-isl_MiDaS_master/midas/dpt_depth.py", line 166, in forward
    return super().forward(x).squeeze(dim=1)
  File "/local/home/lijiaj/.cache/torch/hub/intel-isl_MiDaS_master/midas/dpt_depth.py", line 114, in forward
    layers = self.forward_transformer(self.pretrained, x)
  File "/local/home/lijiaj/.cache/torch/hub/intel-isl_MiDaS_master/midas/backbones/vit.py", line 13, in forward_vit
    return forward_adapted_unflatten(pretrained, x, "forward_flex")
  File "/local/home/lijiaj/.cache/torch/hub/intel-isl_MiDaS_master/midas/backbones/utils.py", line 86, in forward_adapted_unflatten
    exec(f"glob = pretrained.model.{function_name}(x)")
  File "<string>", line 1, in <module>
  File "/local/home/lijiaj/.cache/torch/hub/intel-isl_MiDaS_master/midas/backbones/vit.py", line 68, in forward_flex
    x = blk(x)
  File "/local/home/lijiaj/miniconda3/envs/dngaussian/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/local/home/lijiaj/miniconda3/envs/dngaussian/lib/python3.7/site-packages/timm/models/vision_transformer.py", line 164, in forward
    x = x + self.drop_path1(self.ls1(self.attn(self.norm1(x))))
  File "/local/home/lijiaj/miniconda3/envs/dngaussian/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/local/home/lijiaj/miniconda3/envs/dngaussian/lib/python3.7/site-packages/timm/models/vision_transformer.py", line 86, in forward
    qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, self.head_dim).permute(2, 0, 3, 1, 4)
  File "/local/home/lijiaj/miniconda3/envs/dngaussian/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/local/home/lijiaj/miniconda3/envs/dngaussian/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```

**Comment by Iyeu** [comment]
maybe you can input “unset LD_LIBRARY_PATH”

**Comment by Gwencong** [comment]
> maybe you can input “unset LD_LIBRARY_PATH”

It works for me, but I'm curious why it works
