### ISSUE TITLE
error during training

### ISSUE THREAD

**Issue by lovejoker1102** [Fictionarry/DNGaussian#18]
Traceback (most recent call last):
  File "train_llff.py", line 400, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from, args.near)
  File "train_llff.py", line 95, in training
    render_pkg = render_for_depth(viewpoint_cam, gaussians, pipe, background)
  File "/media/public/disk5/gaohc/huanghy/DNGaussian-main/gaussian_renderer/__init__.py", line 178, in render_for_depth
    rendered_image, radii, rendered_depth, rendered_alpha = rasterizer(
ValueError: not enough values to unpack (expected 4, got 2)

Why did this happen? I thoroughly follow your setting...

**Comment by Fictionarry** [comment]
Hi, I guess you are using the official 3DGS rasterizer to run the code. Indeed our repo requires a modified version from https://github.com/ashawkey/diff-gaussian-rasterization, which has been included in `./submodules`.

**Comment by Fictionarry** [comment]
This is abnormal. The latest reported "eval" results while training should be close to the final results. Please provide more information about which script and which scene and the dataset are used, so that I can try to reproduce this problem.

And please check whether the images have been correctly rendered.

**Comment by Fictionarry** [comment]
Seems the hyperparameters you used are not entirely the same as in our scripts. Ensure `--near` in rendering is the same as in training, otherwise some near contents may be excluded during rendering. It is used to limit the scene range, just like the near and far in NeRFs.

**Comment by 2927803072** [comment]
> 您使用的超参数似乎与我们的脚本中的超参数并不完全相同。确保 in rendering 与 training 相同，否则在渲染过程中可能会排除一些 near 内容。它用于限制场景范围，就像 NeRF 中的近和远一样。`--near`

Hello, why do I get different evaluation results during training than I get when I run the metrics file
training： psnr     13.69
metrics.py：psnr     12.22
and in some scenes, this gap is noticeable
