### ISSUE TITLE
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

### ISSUE THREAD

**Issue by anidealeft** [Fictionarry/DNGaussian#44]
when I  execuate this command:python get_depth_map_for_llff_dtu.py --root_path /home/admin2/code/DNG/DNGaussian/dataset/nerf_llff_data --benchmark LLFF
error occur:
Traceback (most recent call last):
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/http/client.py", line 1443, in connect
    super().connect()
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/http/client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_depth_map_for_llff_dtu.py", line 32, in <module>
    midas = torch.hub.load("intel-isl/MiDaS", model_type)
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/hub.py", line 538, in load
    verbose=verbose, skip_validation=skip_validation)
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/hub.py", line 180, in _get_cache_or_reload
    repo_owner, repo_name, ref = _parse_repo_info(github)
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/site-packages/torch/hub.py", line 133, in _parse_repo_info
    with urlopen(f"https://github.com/{repo_owner}/{repo_name}/tree/main/"):
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/home/admin2/anaconda3/envs/gaussian_splatting/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>

could anyone give me suggestions?thank a lot!!

**Comment by Maple-geekZhu** [comment]
I sometimes encounter this problem, maybe you have internet problem to connect github where you run your code

**Comment by heandrea** [comment]
你可以将MiDaS文件放于/root/.cache/torch/hub/intel-isl/MiDaS，并下载dpt_hybrid_384.pt深度模型。


更改以下代码：
midas = torch.hub.load("/root/.cache/torch/hub/intel-isl/MiDaS", "DPT_Hybrid","/root/.cache/torch/hub/intel-isl/MiDaS/checkpoints/dpt_hybrid_384.pt",source='local')
.......
midas_transforms = torch.hub.load("/root/.cache/torch/hub/intel-isl/MiDaS", "transforms",source="local")
